### ISSUE TITLE
Scale Bar Transform inconsistent

### ISSUE THREAD

**Issue by gpaar** [pro3d-space/PRo3D#380] opened 2024-02-22 15:15 UTC
Coordinate systems are mixed when transforming a scale bar - moving to the North does not lead to moving to the North.
In addition, the annotation of the scale bar stays on its original position, and only the scale bar moves away from it.
In addition, it would be good to be able to rotate the scalebar likewise.

**Comment by haraldsteinlechner** [comment] 2024-02-22 15:54
duplicate of #373

**Closed by haraldsteinlechner** 2024-02-22 15:54 UTC
Labels: bug, Mars 2020, MSL, Rosalind Franklin, HERA, Scale, Annotation
