### ISSUE TITLE
Persistent (Hanging) panning in 3D view when leaving the window

### ISSUE THREAD

**Issue by chris-traxler** [pro3d-space/PRo3D#344] opened 2023-07-04 08:03 UTC
When panning with the middle mouse button in the 3D view and releasing it outside of the 3D view (e.g. in the UI), the release is not recognised. When returning to the 3D view, panning continues without pressed middle mouse button.

Workaround: Click the middle mouse button in the 3D view to stop panning.

**Comment by haraldsteinlechner** [comment] 2024-10-02 08:35
Related, partly subsumed: https://github.com/pro3d-space/PRo3D/issues/192 and https://github.com/pro3d-space/PRo3D/issues/137

My proposal is to upgrade to the new orbit controller - to get rid of deprecation, smoother animation, less threads and maintained pointer apture solution.

The pointer capture problem in free fly is still unclear though.

**Comment by RebeccaNowak** [comment] 2024-10-07 14:11
Should be fixed with pull request #423

**Comment by RebeccaNowak** [comment] 2024-10-08 14:09
More background: FreeFlyController does not seem to recognize when the middle mouse button is released if the cursor is outside the rendering view AND while the middle mouse button is pressed. It works with right and left mouse button. The problem is not PRo3D-specific, it can also be observed in Aardvark.Media in the GoldenLayout Demo. The problem does not occur in the NavigationDemoNew although both use FreeFlyController.

**Closed** 2024-10-15 08:45 UTC
Labels: bug
